title: Cecilia Alberti
logo: "https://github.com/calbertiboms/calbertiboms.github.io/edit/main/_config.yml#:~:text=WhatsApp-,Image,-2024%2D03%2D28"
description: Industrial Mechanical Engineer specializing in Data Science
theme: jekyll-theme-minimal
