title: Cecilia Alberti
description: Industrial Mechanical Engineer specializing in Data Science
profile_image: "/images/profile_picture.jpg"
github_username:  calbertiboms

theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-feed

navigation:
  - title: "GithUB"
    url: "https://github.com/calbertiboms"
  - title: "Resume"
    url: "resume/Cecilia Alberti_Resume.pdf"

