title: Cecilia Alberti
description: Industrial Mechanical Engineer specializing in Data Science
profile_image: "/images/profile_picture.jpg"
github_username:  calbertiboms
theme: jekyll-theme-minimal


